

export const INSERT_MARKS = 'INSERT_MARKS'
export const DELETE_MARKS = 'DELETE_MARKS'
export const RECOVERY_MARKS = 'RECOVERY_MARKS'

export const CREATE_INDEX = 'CREATE_INDEX'
export const REMOVE_INDEX = 'REMOVE_INDEX'
export const RECOVERY_INDEX = 'RECOVERY_INDEX'

export const CLEAR_IMAGE = 'CLEAR_IMAGE'

export const ADMIN_LOGIN = 'ADMIN_LOGIN'
export const ADMIN_LOGOFF = 'ADMIN_LOGOFF'

export const RECOVERY_CONFIG = 'RECOVERY_CONFIG'
export const SET_CONFIG = 'SET_CONFIG'